/**
 *DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/22/2016
 */

'use strict';
angular.module('DigitalNewzealandLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://api.digitalnz.org",

        //Your API Key
        apiKey : ""

    };
});

